services:
  - type: web
    name: mofisafe
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mofisafe.settings
      - key: SECRET_KEY
        value: "django-insecure-ja1^h$mo-&+k#j6+=6*gy#ulge_^w&sjys+3!aw#!#)7dlg%i!"
      - key: DATABASE_URL
        value: mysql://mofisafe_dev:mofisafe_dev_db@198.199.77.247:3306/mofisafe_dev_db
     port: 8000  # Specify the port your Django app will use