# Generated by Django 5.0.6 on 2024-05-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mofisafe_app', '0002_remove_budget_category_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
