# Generated by Django 5.0.6 on 2024-05-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mofisafe_app', '0003_alter_expense_category_alter_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
