# Generated by Django 5.0.6 on 2024-05-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mofisafe_app', '0004_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
